#!/usr/bin/env bash

# check that bin exists & has files
if [ ! -d bin ] || [ -z "$(ls -A bin)" ]; then
	echo "bin/ directory is missing or empty. Please compile first with ./compileandrun." 
	exit
fi

# run project
java -cp bin blockblast.gui.BigGUI
